"""Writers' Room — deterministic, offline-only storyboard builder (Phase 1).

Takes a CampaignBrief and ShopeeProduct and produces a schema-valid
Storyboard (v1) ready for the Editor agent. FR-WR-01..04:

  - Hook scene <= 2.0s
  - Body scenes: avg 1.0-5.0s per Storyboard._avg_shot_in_band
  - CTA scene is last
  - All 6 REQUIRED_EDITOR_PASSES present
  - Total duration <= 60s
  - Consistent consistency_seed across all AiShot siblings (if AiStoryboard
    is also generated by callers)

No LLM, no Anthropic, no httpx, no network calls.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass

from auto_affi.adapters.shopee import ShopeeProduct
from auto_affi.schemas.campaign_brief import CampaignBrief
from auto_affi.schemas.storyboard import (
    REQUIRED_EDITOR_PASSES,
    Dialogue,
    MusicBrief,
    OnScreenText,
    Scene,
    ScenePurpose,
    Storyboard,
    VoiceProfile,
)

# ---------------------------------------------------------------------------
# Deterministic seed generation
# ---------------------------------------------------------------------------

def _derive_seed(brief: CampaignBrief, product: ShopeeProduct) -> int:
    """Derive a deterministic int seed from the brief + product IDs.

    The seed is used as consistency_seed in AiShot; here it also provides
    repeatable shot ordering within a template.
    """
    raw = f"{brief.brief_id}:{product.item_id}:{product.shop_id}"
    digest = hashlib.sha256(raw.encode()).hexdigest()
    # Take the first 8 hex chars → 32-bit positive int
    return int(digest[:8], 16)


# ---------------------------------------------------------------------------
# Scene-level template blocks
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class _SceneSpec:
    duration_s: float
    purpose: ScenePurpose
    shot_type: str
    movement: str
    visual_prompt_template: str  # {product_name} placeholder allowed
    dialogue_th_template: str    # {product_name}, {cta_text} placeholders
    on_screen_th_template: str
    sfx: tuple[str, ...]
    transition_out: str


# 6 scene templates: HOOK → AGITATE → DEMONSTRATE → RESOLVE → SOCIAL_PROOF → CTA
# Durations chosen to satisfy:
#   - scenes[0].duration_s <= 2.0 (hook cap)
#   - avg body shot (scenes[1:]) in [1.0, 5.0]
#   - total <= 60s
# Body shots: 5 scenes x avg 4.4s = 22s; total approx 2 + 22 = 24s (well under 60s)

_SCENE_SPECS: tuple[_SceneSpec, ...] = (
    _SceneSpec(
        duration_s=2.0,
        purpose=ScenePurpose.HOOK,
        shot_type="extreme-closeup",
        movement="snap-zoom-in",
        visual_prompt_template=(
            "Extreme closeup of {product_name}, studio soft-box lighting, "
            "sharp focus on product texture, cool white background, "
            "snap zoom in, high contrast shadows, dynamic energy."
        ),
        dialogue_th_template="รอช้าอยู่ทำไม? {product_name} อยู่นี่แล้ว!",
        on_screen_th_template="🔥 ห้ามพลาด! {product_name}",
        sfx=("whoosh", "bass-hit"),
        transition_out="match-cut",
    ),
    _SceneSpec(
        duration_s=4.0,
        purpose=ScenePurpose.AGITATE,
        shot_type="medium-closeup",
        movement="dolly-in",
        visual_prompt_template=(
            "Medium closeup showing the problem this product solves — "
            "person looking frustrated, warm amber lighting, shallow depth of field, "
            "cinematic 9:16 framing, natural skin tones, relatable everyday scenario."
        ),
        dialogue_th_template="รู้สึกไหมว่าปัญหานี้มันน่ารำคาญมาก?",
        on_screen_th_template="ปัญหาที่คุ้นเคย…",
        sfx=(),
        transition_out="cut",
    ),
    _SceneSpec(
        duration_s=5.0,
        purpose=ScenePurpose.DEMONSTRATE,
        shot_type="overhead",
        movement="rack-focus",
        visual_prompt_template=(
            "Overhead shot demonstrating {product_name} in use, "
            "soft studio lighting, warm amber accents on product, "
            "clean white marble surface, rack focus from hands to product, "
            "premium lifestyle aesthetic, 9:16 vertical framing."
        ),
        dialogue_th_template="ดู! {product_name} ใช้งานได้ง่ายมาก",
        on_screen_th_template="ใช้งานง่าย ผลลัพธ์ชัด",
        sfx=("soft-chime",),
        transition_out="cut",
    ),
    _SceneSpec(
        duration_s=4.0,
        purpose=ScenePurpose.RESOLVE,
        shot_type="medium",
        movement="static",
        visual_prompt_template=(
            "Medium shot of satisfied person using {product_name}, "
            "golden hour warm lighting, genuine smile, natural setting, "
            "result-reveal energy, clean composition, 9:16 framing."
        ),
        dialogue_th_template="หลังใช้ {product_name} ชีวิตง่ายขึ้นมาก!",
        on_screen_th_template="ผลลัพธ์จริง ไม่แต่งภาพ",
        sfx=(),
        transition_out="cut",
    ),
    _SceneSpec(
        duration_s=5.0,
        purpose=ScenePurpose.SOCIAL_PROOF,
        shot_type="wide",
        movement="slow-dolly-right",
        visual_prompt_template=(
            "Wide shot montage feel — multiple happy users with {product_name}, "
            "vibrant lifestyle colours, energetic composition, "
            "social media native aesthetic, 9:16 vertical, warm pink and white palette."
        ),
        dialogue_th_template="คนใช้แล้วกว่าพันคน บอกว่าดีมาก!",
        on_screen_th_template="★★★★★ รีวิวจากลูกค้าจริง",
        sfx=("crowd-cheer-light",),
        transition_out="dissolve",
    ),
    _SceneSpec(
        duration_s=4.0,
        purpose=ScenePurpose.CTA,
        shot_type="product-hero",
        movement="push-in",
        visual_prompt_template=(
            "Hero product shot of {product_name} centred on clean background, "
            "dramatic studio lighting, price tag or CTA overlay space at bottom, "
            "bold and clean composition, Shopee orange accent glow, 9:16 framing."
        ),
        dialogue_th_template="{cta_text} รีบเลย ของมีจำนวนจำกัด!",
        on_screen_th_template="{cta_text}",
        sfx=("cash-register",),
        transition_out="fade-out",
    ),
)

# Total check (for documentation — enforced by schema validator):
# 2.0 + 4.0 + 5.0 + 4.0 + 5.0 + 4.0 = 24.0s  (well within 60s cap)
# Body avg (scenes[1:]) = (4 + 5 + 4 + 5 + 4) / 5 = 4.4s ∈ [1.0, 5.0] ✓


def _render_scene(
    idx: int,
    spec: _SceneSpec,
    product_name: str,
    cta_text: str,
    generator: str = "sora2",
) -> Scene:
    """Instantiate a Scene from a _SceneSpec with substituted text."""
    vprompt = spec.visual_prompt_template.format(product_name=product_name)
    dialogue_th = spec.dialogue_th_template.format(
        product_name=product_name, cta_text=cta_text
    )
    on_screen_th = spec.on_screen_th_template.format(
        product_name=product_name, cta_text=cta_text
    )
    return Scene(
        idx=idx,
        duration_s=spec.duration_s,
        purpose=spec.purpose,
        shot_type=spec.shot_type,
        movement=spec.movement,
        visual_prompt=vprompt,
        generator=generator,
        dialogue=Dialogue(
            speaker="narrator",
            text_th=dialogue_th[:300],
            emphasis_words=[],
        ),
        on_screen_text=OnScreenText(
            th=on_screen_th[:120],
            style="bold-pop",
            position="center-upper",
        ),
        sfx=list(spec.sfx),
        transition_out=spec.transition_out,
    )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def build_storyboard(
    brief: CampaignBrief,
    product: ShopeeProduct,
) -> Storyboard:
    """Build a deterministic, schema-valid Storyboard from a brief + product.

    The mapping is:
      product name keywords + hook_template_slug → 6 fixed scene specs
      (hook 2s → agitate 4s → demonstrate 5s → resolve 4s → social_proof 5s
       → cta 4s) = 24s total.

    All schema validators pass:
      - scenes[0].purpose == HOOK, duration_s <= 2.0
      - avg body shot 4.4s ∈ [1.0, 5.0]
      - total 24.0s <= 60.0
      - cta_scene_idx points to scenes[-1] whose purpose == CTA
      - all 6 REQUIRED_EDITOR_PASSES present

    Parameters
    ----------
    brief:
        The CampaignBrief produced by build_brief().
    product:
        The ShopeeProduct used to personalise visual prompts.

    Returns
    -------
    Storyboard
        A fully-populated, pydantic-validated storyboard.
    """
    product_name = product.name
    cta_text = brief.cta.text_th

    scenes = [
        _render_scene(idx, spec, product_name, cta_text)
        for idx, spec in enumerate(_SCENE_SPECS)
    ]

    cta_idx = len(scenes) - 1

    return Storyboard(
        brief_id=brief.brief_id,
        voice_profile=VoiceProfile(
            lang="th",
            gender="f",
            tone="energetic-confident",
            tts_engine="elevenlabs",
            voice_id="auto",
        ),
        music_brief=MusicBrief(
            genre="upbeat-pop",
            bpm_range=(110, 130),
            license="epidemic-sound",
        ),
        scenes=scenes,
        cta_scene_idx=cta_idx,
        affiliate_link_placement="pinned_comment + on_screen_qr",
        editor_passes=list(REQUIRED_EDITOR_PASSES),
    )
